CREATE DATABASE board DEFAULT CHARACTER SET=utf8;

CREATE TABLE users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  password VARCHAR(8) NOT NULL,
  name VARCHAR(11) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE comments(
  id INT AUTO_INCREMENT PRIMARY KEY,
  comment TEXT NOT NULL,
  userId INT NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO users (userId,password,name) values(1,a,太朗);
